import org.junit.Test
import com.twf.visualization.ColoringTask
import com.twf.visualization.brushMathMl
import com.twf.visualization.dropPerformedBrushing
import kotlin.test.assertEquals

class VisualizationTests {

    @Test
    fun dropColoring() {
        val string = "<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mn>2</mn><mi>a</mi><mo>+</mo><mn>8</mn><mo mathcolor=\"#FF3456\">&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo mathcolor=\"#12FF56\">&gt;</mo><mn>6</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mo>[</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo mathcolor=\"#1234FF\">=</mo><mo mathcolor=\"#1234FF\">&gt;</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi><mrow mathcolor=\"#123456\"><mo>=</mo><mo>&gt;</mo></mrow><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>]</mo><mspace linebreak=\"newline\"/><mo>[</mo><mtext>sin2:</mtext><mi>sin</mi><mo>(</mo><mn>2</mn><mi>a</mi><mo>)</mo><mo>=</mo><mi>sin</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>)</mo><mo>=</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>a</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>a</mi><mo>)</mo><mo>]</mo><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mo>[</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>=</mo><mo>&gt;</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mo>-</mo><mn>1</mn><mo>]</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mo>(</mo><mo>-</mo><mn>1</mn><mo>)</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn><mo>&#xA0;</mo><mo>=</mo><mo>&gt;</mo><mtext>sin2:</mtext><mo>&#x21D2;</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>b</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced></math>"
        val unbrushed = dropPerformedBrushing(string)
        assertEquals("<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mn>2</mn><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mo>[</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>]</mo><mspace linebreak=\"newline\"/><mo>[</mo><mtext>sin2:</mtext><mi>sin</mi><mo>(</mo><mn>2</mn><mi>a</mi><mo>)</mo><mo>=</mo><mi>sin</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>)</mo><mo>=</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>a</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>a</mi><mo>)</mo><mo>]</mo><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mo>[</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>=</mo><mo>&gt;</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mo>-</mo><mn>1</mn><mo>]</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mo>(</mo><mo>-</mo><mn>1</mn><mo>)</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn><mo>&#xA0;</mo><mo>=</mo><mo>&gt;</mo><mtext>sin2:</mtext><mo>&#x21D2;</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>b</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced></math>",
                unbrushed)
    }

    @Test
    fun brushing(){
        val string = "<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mn>2</mn><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mo>[</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>]</mo><mspace linebreak=\"newline\"/><mo>[</mo><mtext>sin2:</mtext><mi>sin</mi><mo>(</mo><mn>2</mn><mi>a</mi><mo>)</mo><mo>=</mo><mi>sin</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>)</mo><mo>=</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>a</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>a</mi><mo>)</mo><mo>]</mo><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mo>[</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>=</mo><mo>&gt;</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mo>-</mo><mn>1</mn><mo>]</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mo>(</mo><mo>-</mo><mn>1</mn><mo>)</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn><mo>&#xA0;</mo><mo>=</mo><mo>&gt;</mo><mtext>sin2:</mtext><mo>&#x21D2;</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>b</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced></math>"
        val tasks = listOf<ColoringTask>(
                ColoringTask(436, 459, "008800"),
                ColoringTask(552, 578, "008800"),
                ColoringTask(658, 658, "008888"),
                ColoringTask(76, 334, "000088"),
                ColoringTask(971, 1455, "0088FF"),
                ColoringTask(1521, 2127, "00FF00")
        )
        val brushed = brushMathMl(string, tasks)
        assertEquals("<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mfenced open=\"{\" close=\"\"><mrow mathvariant=\"bold\" mathcolor=\"#000088\"><mtable columnalign=\"left\"><mtr><mtd><mn>2</mn><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn></mtd></mtr></mtable></mrow></mfenced><mspace linebreak=\"newline\"/><mo>[</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mrow mathvariant=\"bold\" mathcolor=\"#008800\"><mo>=</mo><mo>&gt;</mo></mrow><mi>a</mi><mo>+</mo><mi>a</mi><mo>+</mo><mn>8</mn><mo>&lt;</mo><mn>9</mn><mo>+</mo><mi>a</mi><mrow mathvariant=\"bold\" mathcolor=\"#008800\"><mo>=</mo><mo>&gt;</mo></mrow><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>]</mo><mspace linebreak=\"newline\"/><mo>[</mo><mrow mathvariant=\"bold\" mathcolor=\"#008888\"><mi>_</mi></mrow><mtext>sin2:</mtext><mi>sin</mi><mo>(</mo><mn>2</mn><mi>a</mi><mo>)</mo><mo>=</mo><mi>sin</mi><mo>(</mo><mi>a</mi><mo>+</mo><mi>a</mi><mo>)</mo><mo>=</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>a</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>a</mi><mo>)</mo><mo>]</mo><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mrow mathvariant=\"bold\" mathcolor=\"#0088FF\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>=</mo><mo>&gt;</mo><mi>a</mi><mo>+</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi></mtd></mtr></mtable></mrow></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mrow mathvariant=\"bold\" mathcolor=\"#00FF00\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mi>a</mi><mo>=</mo><mo>&gt;</mo><mo>[</mo><mi>a</mi><mo>&lt;</mo><mn>1</mn><mo>=</mo><mo>&gt;</mo><mo>-</mo><mi>a</mi><mo>&gt;</mo><mo>-</mo><mn>1</mn><mo>]</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>6</mn><mo>-</mo><mo>(</mo><mo>-</mo><mn>1</mn><mo>)</mo><mo>=</mo><mo>&gt;</mo><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mrow></mfenced><mspace linebreak=\"newline\"/><mfenced open=\"{\" close=\"\"><mtable columnalign=\"left\"><mtr><mtd><mi>a</mi><mo>&lt;</mo><mn>1</mn></mtd></mtr><mtr><mtd><mi>sin</mi><mo>(</mo><mn>2</mn><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn><mo>&#xA0;</mo><mo>=</mo><mo>&gt;</mo><mtext>sin2:</mtext><mo>&#x21D2;</mo><mn>2</mn><mi>sin</mi><mo>(</mo><mi>b</mi><mo>)</mo><mi>cos</mi><mo>(</mo><mi>b</mi><mo>)</mo><mo>&gt;</mo><mn>5</mn></mtd></mtr></mtable></mfenced></math>",
                brushed)
    }
}